// @ts-check

import fs from 'node:fs';
import path from 'node:path';

const docsDir = path.resolve('docs');
const servicesDir = path.join(docsDir, 'services');

function frontMatterTitle(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const match = content.match(/^title:\s*(.+)$/m);
  if (!match) {
    return path.basename(filePath, '.md');
  }

  try {
    return JSON.parse(match[1]);
  } catch {
    return match[1].replace(/^["']|["']$/g, '');
  }
}

const serviceItems = fs
  .readdirSync(servicesDir)
  .filter((fileName) => fileName.endsWith('.md'))
  .sort()
  .map((fileName) => {
    const serviceKey = path.basename(fileName, '.md');
    const articleDir = `services/${serviceKey}`;
    const articlePath = path.join(docsDir, articleDir);

    return {
      type: 'category',
      label: frontMatterTitle(path.join(servicesDir, fileName)),
      className: `service-sidebar-item service-sidebar-${serviceKey}`,
      customProps: {
        serviceKey,
      },
      link: {
        type: 'doc',
        id: `services/${serviceKey}`,
      },
      items: fs.existsSync(articlePath)
        ? [{type: 'autogenerated', dirName: articleDir}]
        : [],
    };
  });

const sidebars = {
  briefingSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Today in Tech',
    },
    ...serviceItems,
  ],
};

export default sidebars;
